[tool.black]
line-length = 100
target-version = ["py311"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | venv
  | build
  | dist
  | __pycache__
  | .*migrations.*
)/
'''

[tool.ruff]
src = ["backend"]
target-version = "py311"
line-length = 100

[tool.ruff.lint]
select = [
  "E",    # pycodestyle errors
  "F",    # pyflakes
  "I",    # isort (import sorting via Ruff)
  "UP",   # pyupgrade
  "B",    # flake8-bugbear
  "TCH",  # flake8-type-checking (import-in-type-checking)
]
ignore = [
  "E203", # keep compatible with Black's slicing whitespace
]

[tool.ruff.lint.per-file-ignores]
"backend/**/__init__.py" = ["F401"]

# (Only used if you run `ruff format`. Safe to keep.)
[tool.ruff.format]
quote-style = "preserve"
